### ISSUE TITLE
Add Typescript declaration

### ISSUE THREAD

**Issue by kernwig** [filipdanic/compact-timezone-list#3]
This library is _really_ hard to import into a Typescript project.
A couples lines in a `.d.ts` file de declare the two imports would make it easy.

**Comment by filipdanic** [comment]
Feel free to make a pull request with these and I’ll be happy to merge and publish a new version! :)

**Comment by kernwig** [comment]
Turns out that the problem has nothing to do with Typescript. It doesn't work with Node.js v12.

```
const tz = require("compact-timezone-list");
console.log(tz);
```
$ node test.js
```
export default [
^^^^^^

SyntaxError: Unexpected token 'export'
```

The ES2015 module style in the source isn't compatible with Node.js v12 (which is as high as I can go right now).
I don't know how to fix this without possibly breaking the library for anyone else already dependent upon this file being an ES module. @filipdanic

**Comment by kernwig** [comment]
@filipdanic 
I created a PR that attempts to expand this library to work with CommonJS as well as ES Modules, and adds Typescript declarations. I am struggling with figuring out how to test it without publishing, but before going farther I figured I had best get your blessing on the addition.

**Comment by abdullahmujahidali** [comment]
Using Typescript is the only option? I am working on a non-typescript project in next JS.

**Comment by wparad** [comment]
No but the PR #5 solves both issues.
